# In Silico Protein Digestion using Rapid Peptides Generator

Rapid Peptides Generator (RPG), is a standalone software dedicated to predict proteases-induced cleavage sites on sequences.

RPG is a python tool taking a (multi-)fasta/fastq file of proteins as input and digest each of them. The digestion mode can be either ‘concurrent’, i.e. all enzymes are present at the same time during digestion, or ‘sequential’. In sequential mode, each protein will be digested by each enzyme, one by one.

The resulting peptides contain information about positions of cleavage site, peptide sequences, length, mass as well as an estimation of isoelectric point (pI) of each peptide. Results are outputted in multi-fasta, CSV or TSV file.

# Setup
## Import and install Packages

In [63]:
import sys
import os
import session_info

# Add the '0_functions' folder to sys.path
sys.path.append(os.path.join(os.getcwd(), '..', '00_functions'))

In [64]:
import pandas as pd
import re
from functions import read_fastafile

In [65]:
# Display session information
session_info.show()

In [66]:
!pip install rpg

Requirement already satisfied: rpg in /opt/anaconda3/envs/isoform_database/lib/python3.8/site-packages (2.0.5)

In [67]:
!rpg --help

usage: rpg [-h] [-a] [-b str] [-d str] [-e str [str ...]] [-f str] [-i path]
           [-l] [-s str] [-m float [float ...] | -t int [int ...]] [-n]
           [-x str [str ...]] [-z str [str ...]] [-y str] [-p str] [-w str]
           [-o str | -r] [-c int] [-q | -v] [--version]

This software takes protein sequences as input (-i option). All sequences will
be cleaved according to selected enzymes (-e option) and given miscleavage
percentage (-m option). Cleaving can be sequential or concurrent (-d option).
Resulting peptides are outputted in a file (-o option) in fasta, csv or tsv
format (-f option). Classical enzymes are included (-l option to print
available enzymes) but it is possible to define other enzymes (-a option). See
https://gitlab.pasteur.fr/nmaillet/rpg/ and https://rapid-peptide-
generator.readthedocs.io for more informations.

optional arguments:
  -h, --help            show this help message and exit
  -a, --addenzyme       Create a new enzyme. See https://rapid-peptide-
                        generator.readthedocs.io for more information
  -b str, --delenzyme str
                        Delete a user-define enzyme. See https://rapid-
                        peptide-generator.readthedocs.io for more information
  -d str, --digest str  Digestion mode. Either 's', 'sequential', 'c' or
                        'concurrent' (default: s)
  -e str [str ...], --enzymes str [str ...]
                        Id or name of enzyme(s) to use (e.g. -e 1 Asp-N 10 to
                        use enzymes 1, Asp-N and 10). Use -l first to get
                        enzyme ids or names
  -f str, --fmt str     Output file format. Either 'fasta', 'csv', or 'tsv'
                        (default: fasta)
  -i path, --inputdata path
                        Input file, in fasta / fastq format (gzipped or not)
  -l, --list            Display the list of available enzymes
  -s str, --sequence str
                        Input a single protein sequence without commentary
  -m float [float ...], --miscleavage float [float ...]
                        Percentage of miscleavage, between 0 and 100, by
                        enzyme(s). It should be in the same order than
                        -enzymes options (e.g. -m 15 5 10). Only for
                        sequential digestion (default: 0)
  -t int [int ...], --theoretical int [int ...]
                        Maximum number of miscleavages, by enzyme(s). RPG will
                        produce all theoretical peptides allowing at most -t
                        miscleavages. It should be in the same order than
                        -enzymes options (e.g. -t 1 3 2). Only for sequential
                        digestion (default: 0)
  -n, --noninteractive  Non-interactive mode. No standard output, only
                        error(s) (--quiet enable, overwrite -v). If output
                        filename already exists, output file will be
                        overwritten.
  -x str [str ...], --cleave str [str ...]
                        Cleavage site(s) when adding enzyme in non-interactive
                        (e.g. -x "(D or E,)" or -x "(D,)" "(E,)"
  -z str [str ...], --exception str [str ...]
                        Exception(s) when adding enzyme in non-interactive
                        (e.g. -z "(D,)(W)" "(D,)(A)"
  -y str, --enzname str
                        Enzyme's name when adding enzyme in non-interactive.
  -p str, --pka str     Define pKa values. Either 'ipc2' 'stryer' or 'ipc'
                        (default: ipc2)
  -w str, --mass str    Define atomic mass values. Either 'avg' for average
                        mass or 'mono' for monoisotopic mass (default: avg)
  -o str, --outputfile str
                        Optional result file to output result peptides.
  -r, --randomname      Random (not used) output file name
  -c int, --processes int
                        Number of parallel processes to use (default: 1)
  -q, --quiet           No standard output, only error(s)
  -v, --verbose         Increase output verbosity. -vv will increase more than
                        -v
  --version             show program's version number and exit

## Set working directory

In [68]:
cwd = os.getcwd()
if not cwd.endswith("Isoform_Database/Jupyter_environment/02_In-Silico_Digestion"):
    print("WARNING: The working directory is not set to the '02_In-Silico_Digestion'!")
    print("Current working directory:", cwd)
else:
    print(f"Working directory is correctly set to the '02_In-Silico_Digestion' folder (\"{cwd}\").")

WARNING: The working directory is not set to the '02_In-Silico_Digestion'!
Current working directory: /Users/lauranieba/Documents/Uni/Master_ETH/FS26/Lab_Rotation_Davos/Isoform_Database/Jupyter_environment/Isoform_Database_SIAF/02_In-Silico_Digestion

In [69]:
# Data directory for fasta data
input_dir = "data/digestion_input"
output_dir = "data/digestion_output"
fasta_dir = "../01_UniProt/data/raw_data/fasta"

## Read in Fasta files

In [70]:
fasta_canonical = os.path.join(fasta_dir, 'uniprotkb_canonical_2026_03_31.fasta')
fasta_full_proteome = os.path.join(fasta_dir, 'uniprotkb_full_proteome_2026_03_31.fasta')
fasta_alternative_product = os.path.join(fasta_dir, 'uniprotkb_alternative_products_isoforms_2026_03_31.fasta')

# Performing digestion with RPG

In [71]:
#Show list of possible Enzymes to check which number is Trypsin (42)
!rpg -l

1: Arg-C
2: Asp-N
3: BNPS-Skatole
4: Bromelain
5: Caspase-1
6: Caspase-2
7: Caspase-3
8: Caspase-4
9: Caspase-5
10: Caspase-6
11: Caspase-7
12: Caspase-8
13: Caspase-9
14: Caspase-10
15: Chymotrypsin-high
16: Chymotrypsin-low
17: Clostripain
18: CNBr
19: Enterokinase
20: Factor-Xa
21: Ficin
22: Formic-acid
23: Glu-C
24: Glutamyl-endopeptidase
25: Granzyme-B
26: Hydroxylamine
27: Iodosobenzoic-acid
28: Lys-C
29: Lys-N
30: Neutrophil-elastase
31: NTCB
32: Papain
33: Pepsin-pH1.3
34: Pepsin-pH>=2
35: Proline-endopeptidase
36: Proteinase-K
37: Staphylococcal-peptidase-I
38: Thermolysin
39: Thrombin
40: Thrombin-SG
41: Tobacco-Etch-Virus
42: Trypsin
43: Asp-N Endopeptidase
44: ProAlanase
45: Elastase
46: aLP

Trial run with only canonical forms that have isoforms (~10'000 proteins).

!rpg -i ../01_UniProt/data/raw_data/fasta/uniprotkb_alternative_products_canonical_2026_04_05.fasta -o data/digestion_isoforms_canonical.fasta -e 42 -v

# from fasta to pd dataframe
digestion_isoforms_canonical = read_fastafile(os.join.path(output_dir, 'digestion_isoforms_canonical.fasta'))

digestion_isoforms_canonical

For the digestion of the entire proteome I used Euler. The script that I used is shown below. The fragments are filtered so that we only keep the ones that are 7 amino acids long or longer.

#!/bin/bash
#SBATCH --job-name=rpg_digestion
#SBATCH --output=rpg_%j.out
#SBATCH --error=rpg_%j.err
#SBATCH --ntasks=1
#SBATCH --time=12:00:00
#SBATCH --mem-per-cpu=8G

# 1. Load the same Python module used for installation
module load stack/2024-06 python/3.11.6

# 2. Activate environment
source ~/rpg_env/bin/activate

# 3. Run the digestion
rpg -i fasta_no_duplicates.fasta -m 20 -o digestion_full_proteome_unique.fasta -e 42 -v

In [72]:
digestion_full_proteome_unique = read_fastafile(os.path.join(output_dir, 'digestion_full_proteome_unique.fasta'))

In [73]:
digestion_full_proteome_filtered = digestion_full_proteome_unique[digestion_full_proteome_unique["len"] >= 7]
digestion_full_proteome_filtered = digestion_full_proteome_filtered[digestion_full_proteome_filtered["len"] <= 52]

In [74]:
digestion_full_proteome_filtered

,ID,seqID,seq,len
0,A0A087X1C5,sp|A0A087X1C5|CP2D7_HUMAN,MGLEALVPLAMIVAIFLLLVDLMHR,25
3,A0A087X1C5,sp|A0A087X1C5|CP2D7_HUMAN,YPPGPLPLPGLGNLLHVDFQNTPYCFDQLR,30
5,A0A087X1C5,sp|A0A087X1C5|CP2D7_HUMAN,FGDVFSLQLAWTPVVVLNGLAAVR,24
7,A0A087X1C5,sp|A0A087X1C5|CP2D7_HUMAN,GEDTADRPPAPIYQVLGFGPR,21
8,A0A087X1C5,sp|A0A087X1C5|CP2D7_HUMAN,SQGVILSR,8
...,...,...,...,...
2647293,A6NHP3-2_Q495Y8-2,sp|A6NHP3-2_Q495Y8-2|SPE2B_SPDE2_HUMAN,QNIFHFLYR,9
2647298,A6NHP3-2_Q495Y8-2,sp|A6NHP3-2_Q495Y8-2|SPE2B_SPDE2_HUMAN,KPWFQLGSMNPR,12
2647322,A6NHP3-2_Q495Y8-2,sp|A6NHP3-2_Q495Y8-2|SPE2B_SPDE2_HUMAN,SQIVLFQK,8
2647325,A6NHP3-2_Q495Y8-2,sp|A6NHP3-2_Q495Y8-2|SPE2B_SPDE2_HUMAN,FHFFCSMSCR,10
2647326,A6NHP3-2_Q495Y8-2,sp|A6NHP3-2_Q495Y8-2|SPE2B_SPDE2_HUMAN,AWVSPEELEEIQAYDPEHWVWAR,23

In [75]:
#save filtered df as csv
digestion_full_proteome_filtered.to_csv(os.path.join(output_dir, 'digestion_full_proteome_filtered.csv'), index=False)

The digestion was redone with 20% miscleavage to get longer peptides that could potentially be used as unique peptides for isoforms that are truncated versions of the canonical protein.

In [76]:
digestion_m20_full_proteome_unique = read_fastafile(os.path.join(output_dir, 'digestion_m20_full_proteome_unique.fasta'))

In [77]:
digestion_m20_full_proteome_filtered = digestion_m20_full_proteome_unique[digestion_m20_full_proteome_unique["len"] >= 7]
digestion_m20_full_proteome_filtered = digestion_m20_full_proteome_filtered[digestion_m20_full_proteome_filtered["len"] <= 52]

In [78]:
digestion_m20_full_proteome_filtered

,ID,seqID,seq,len
0,A0A087X1C5,sp|A0A087X1C5|CP2D7_HUMAN,MGLEALVPLAMIVAIFLLLVDLMHR,25
2,A0A087X1C5,sp|A0A087X1C5|CP2D7_HUMAN,WAARYPPGPLPLPGLGNLLHVDFQNTPYCFDQLR,34
4,A0A087X1C5,sp|A0A087X1C5|CP2D7_HUMAN,FGDVFSLQLAWTPVVVLNGLAAVR,24
6,A0A087X1C5,sp|A0A087X1C5|CP2D7_HUMAN,GEDTADRPPAPIYQVLGFGPRSQGVILSR,29
7,A0A087X1C5,sp|A0A087X1C5|CP2D7_HUMAN,YGPAWREQR,9
...,...,...,...,...
2125926,A6NHP3-2_Q495Y8-2,sp|A6NHP3-2_Q495Y8-2|SPE2B_SPDE2_HUMAN,IPLLRKPWFQLGSMNPR,17
2125929,A6NHP3-2_Q495Y8-2,sp|A6NHP3-2_Q495Y8-2|SPE2B_SPDE2_HUMAN,SRIPLLR,7
2125945,A6NHP3-2_Q495Y8-2,sp|A6NHP3-2_Q495Y8-2|SPE2B_SPDE2_HUMAN,NRSQIVLFQK,10
2125947,A6NHP3-2_Q495Y8-2,sp|A6NHP3-2_Q495Y8-2|SPE2B_SPDE2_HUMAN,RFHFFCSMSCR,11
2125948,A6NHP3-2_Q495Y8-2,sp|A6NHP3-2_Q495Y8-2|SPE2B_SPDE2_HUMAN,AWVSPEELEEIQAYDPEHWVWAR,23

In [79]:
#save filtered df as csv
digestion_m20_full_proteome_filtered.to_csv(os.path.join(output_dir, 'digestion_m20_full_proteome_filtered.csv'), index=False)